#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────
# validate.sh
# Runs a check-only delta deployment against the target org and saves
# the resulting Job ID for quick deploy.
#
# Required env vars:
#   TARGET_ORG_ALIAS   — sf org alias for the target org
#
# Required files:
#   delta-package/package/package.xml   — generated by generate-delta-package.sh
#   manifest/testclass/testclass.txt    — comma or space separated test class names
#
# Outputs:
#   deploy-result.json   — full JSON result from sf CLI
#   DEPLOY_JOB_ID        — written to $GITHUB_ENV for use in quick-deploy job
# ─────────────────────────────────────────────────────────────────────

set -euo pipefail

TARGET_ORG_ALIAS="${ORG_ALIAS}"
PACKAGE_XML="delta-package/package/package.xml"
TEST_CLASS_FILE="manifest/testclass/testclass.txt"
RESULT_FILE="./DEPLOY_ORG.txt"

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo " Delta Check-Only Validation"
echo " Target org  : $TARGET_ORG_ALIAS"
echo " Package     : $PACKAGE_XML"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# ── Guard: skip if delta package is empty ─────────────────────────
if ! grep -q "<types>" "$PACKAGE_XML"; then
  echo "⚠️   No metadata changes in delta package — skipping validation."
  echo "DELTA_HAS_CHANGES=false" >> "${GITHUB_ENV:-/dev/null}"
  exit 0
fi

# ── Read test classes from file ───────────────────────────────────
# testclass.txt should have class names separated by newlines or spaces
TEST_CLASSES=$(cat "$TEST_CLASS_FILE")
echo "    Test classes : $TEST_CLASSES"
echo ""

# ── Run check-only deployment ─────────────────────────────────────
# --json gives us structured output so we can reliably extract the Job ID
# sf project deploy start \
#   --manifest       "$PACKAGE_XML" \
#   --target-org     "$TARGET_ORG_ALIAS" \
#   --dry-run \
#   --test-level     RunSpecifiedTests \
#   --tests          "$TEST_CLASSES" \
#   --json \
#   --wait           60 \
#   | tee "$RESULT_FILE"

  sf project deploy start -o $TARGET_ORG_ALIAS -x $PACKAGE_XML -l RunSpecifiedTests -t $(cat $TEST_CLASS_FILE) --verbose --dry-run --async --ignore-conflicts | tee $RESULT_FILE 


DEPLOY_EXIT_CODE=${PIPESTATUS[0]}

# ── Extract Job ID from JSON output ───────────────────────────────
# jq parses the structured JSON — no fragile string slicing
DEPLOY_JOB_ID=$(jq -r '.result.id' "$RESULT_FILE")

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo " Deploy Job ID : $DEPLOY_JOB_ID"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# ── Write Job ID to GitHub Actions environment ────────────────────
# This makes DEPLOY_JOB_ID available to downstream jobs in the pipeline
echo "DEPLOY_JOB_ID=$DEPLOY_JOB_ID"     >> "${GITHUB_ENV:-/dev/null}"
echo "DELTA_HAS_CHANGES=true"           >> "${GITHUB_ENV:-/dev/null}"

# ── Exit with deploy exit code ────────────────────────────────────
if [ "$DEPLOY_EXIT_CODE" != "0" ]; then
  echo ""
  echo "❌  Validation failed — check deploy-result.json for details."
  exit "$DEPLOY_EXIT_CODE"
fi

echo ""
echo "✅  Validation passed — Job ID saved for quick deploy."