# Define a workflow to execute deployment upon merge into specific branches
name: Auto Deployment

# Trigger the workflow on merge events into specific branches
on:
  push:
    branches:
      - "qa"

jobs:
  # Job to deploy components to the QA environment
  qa-promote:
    if: ${{ github.event_name == 'push' && github.ref_name == 'qa' }}
    name: QA
    # Utilizing the dynamic yml file for reusability
    uses: ./.github/workflows/deployment-workflow.yml
    with:
      WORKFLOW_TYPE: DEPLOYMENT
      AUTH_ORG_ALIAS: Qa
    secrets:
      SF_INSTANCE_URL: ${{secrets.SF_INSTANCE_URL}}
      SF_USERNAME: ${{secrets.SF_USERNAME}}
      SF_JWT_PRIVATE_KEY: ${{ secrets.SF_JWT_PRIVATE_KEY }}
      SF_CLIENT_ID: ${{secrets.SF_CONSUMER_KEY}}

