# Pull request validation initiation
name: Pull Request (PR) Validation

# Controls when the action will run.
on:
  # Trigger the PR validation on pull request with master branch
  pull_request:
    branches:
      - "uat/main"
jobs:
  # Validate the Commit against Ci Org to ensure nothing is conflicting.
  build:
    name: PR Validation
    # Utilizing the dynamic yml file for reusability
    uses: ./.github/workflows/pr-validation-workflow.yml
    with:
      WORKFLOW_TYPE: PRVALIDATION
      AUTH_ORG_ALIAS: UAT
      BASE_BRANCH: ${{ github.base_ref }}
    secrets:
      SF_INSTANCE_URL: ${{secrets.SF_INSTANCE_URL}}
      SF_USERNAME: ${{secrets.SF_USERNAME}}
      SF_JWT_PRIVATE_KEY: ${{ secrets.SF_JWT_PRIVATE_KEY }}
      SF_CLIENT_ID: ${{secrets.SF_CONSUMER_KEY}}
      # DOCKER_HUB_UN: ${{secrets.DOCKER_HUB_USERNAME}}
      # DOCKER_HUB_PW: ${{secrets.DOCKER_HUB_PASSWORD}}
