# Pull request validation initiation
name: PR Validation

# Controls when the action will run. 
on:
  # Trigger the PR validation on pull request with master branch
    pull_request:
        branches: [dev, qa, uat, master]
jobs:
  # Validate the Commit against Ci Org to ensure nothing is conflicting.
  build:
    name: build
    # Utilizing the dynamic yml file for reusability
    uses: ./.github/workflows/validation-workflow.yml
    with:
      SOURCE_ORG_ALIAS: CI
      BASE_BRANCH: ci
    secrets:
      SECRET_URL_PATH: ${{secrets.CI_ORG_AUTH_URL}}
      DOCKER_HUB_UN: ${{secrets.DOCKER_HUB_USERNAME}}
      DOCKER_HUB_PASS: ${{secrets.DOCKER_HUB_PASSWORD}}